export const QUESTION_LOAD_SUCCESS = "QUESTION_LOAD_SUCCESS";
export const QUESTION_LOAD_BY_CATEGORY_SUCCESS = "QUESTION_LOAD_BY_CATEGORY_SUCCESS";
export const CATEGORIES_LOAD_SUCCESS = "CATEGORIES_LOAD_SUCCESS";
export const SET_ANSWER = "SET_ANSWER";
